#!/usr/bin/env python3
"""gen_gif_index — regenerate GIF_INDEX.md from series_state.json.

GIF_INDEX.md is the human-readable table of every GIF in the repo; the
ledger is the source of truth. Run this after editing series_state.json
(tools/check_series.py first) so the two never drift. Output is fully
determined by the ledger — no dates — so a rerun on an unchanged ledger is
a no-op diff. A null group renders as "—".

Usage: python3 tools/gen_gif_index.py [--state PATH] [--out PATH]
"""
import argparse
import os
import sys
import urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from check_series import ROOT, STATE_PATH, load_state, personal_numbers, subject_key  # noqa: E402

INDEX_PATH = os.path.join(ROOT, "GIF_INDEX.md")
NO_GROUP = "—"


def cell(text: str | None) -> str:
    """One markdown table cell: pipes escaped, whitespace (line breaks above all,
    which would end the row early) collapsed to single spaces, None shown as an
    em dash."""
    return NO_GROUP if text is None else " ".join(str(text).split()).replace("|", "\\|")


def link(f: str) -> str:
    """A markdown link to a root-level file: the label escaped like any other
    cell (plus `]`), the target percent-encoded so no character in a filename
    can break out of the link."""
    return "[%s](%s)" % (cell(f).replace("]", "\\]"), urllib.parse.quote(f, safe="._-"))


def episode_rows(done: list[dict]) -> list[str]:
    rows = []
    for e, num in zip(done, personal_numbers(done)):
        rows.append((e["subject"].lower(), num, "| %s | %s | %02d | %s | %s | %s |" % (
            cell(e["subject"]), cell(e.get("group")), num, cell(e["style"]),
            link(e["file"]), cell(e["topic"]))))
    return [r for _, _, r in sorted(rows)]


def one_off_rows(one_offs: list[dict]) -> list[str]:
    return ["| %s | %s | %s |" % (link(e["file"]), cell(e["style_base"]), cell(e["topic"]))
            for e in one_offs]


def group_notes(done: list[dict]) -> list[str]:
    """One line per group, subjects in first-appearance order, like the hand-written index had."""
    by_group: dict[str | None, list[str]] = {}
    for e in done:
        names = by_group.setdefault(e.get("group"), [])
        if e["subject"] not in names:
            names.append(e["subject"])
    return ["- %s subjects: %s (%d)" % (cell(g), ", ".join(names), len(names))
            for g, names in by_group.items()]


def render_index(state: dict) -> str:
    done = state.get("done", [])
    one_offs = state.get("one_offs", [])
    n_subjects = len({subject_key(e["subject"]) for e in done})
    lines = [
        "# GIF Index — CLIPWRIGHT_PLAN",
        "",
        "Generated by [tools/gen_gif_index.py](tools/gen_gif_index.py) from "
        "[series_state.json](series_state.json), the source of truth for the series rotation — "
        "edit the ledger and rerun the tool rather than this file. One-offs are the standalone "
        "gags outside the coworker rotation; each is marked as such in its own script.",
        "",
        "## Counts",
        "",
        "- **%d series** (one per coworker), **%d episodes** total" % (n_subjects, len(done)),
        "- **%d one-off** gags (not tied to any coworker/series)" % len(one_offs),
        "- **%d GIFs** total" % (len(done) + len(one_offs)),
        "",
        "## Series episodes",
        "",
        "| Subject | Group | Ep | Style | File | Topic |",
        "|---|---|---|---|---|---|",
        *episode_rows(done),
        "",
        "## One-offs",
        "",
        "| File | Style base | Topic |",
        "|---|---|---|",
        *one_off_rows(one_offs),
        "",
        "## Notes",
        "",
        *group_notes(done),
        "- Style rotation is global, not per subject: each new episode takes the style after the "
        "most recent `done` entry's, whoever its subject is (tabloid → ballad → meme → tabloid → ..., "
        "per `rules` in series_state.json and plan_episode.py); one-offs reuse a kit's visuals but "
        "skip the verbatim-quote rule.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--state", default=STATE_PATH)
    ap.add_argument("--out", default=INDEX_PATH)
    args = ap.parse_args(argv)
    text = render_index(load_state(args.state))
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d lines)" % (args.out, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
